version: 2.1

jobs:
  deploy:
    docker:
      - image: denoland/deno:2.3.3
    steps:
      - checkout
      - run:
          name: Install Val Town CLI (vt)
          command: deno install -grAf jsr:@valtown/vt
      - run:
          name: Push to Val Town
          command: vt push

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
